/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BuilderTableNameRouteImport } from './routes/builder.$tableName'
import { Route as ListTableNameRouteImport } from './routes/list.$tableName'
import { Route as UiBuilderIndexRouteImport } from './routes/ui-builder.index'
import { Route as UiBuilderPageIdRouteImport } from './routes/ui-builder.$pageId'
import { Route as WidgetBuilderIndexRouteImport } from './routes/widget-builder.index'
import { Route as WidgetBuilderWidgetIdRouteImport } from './routes/widget-builder.$widgetId'
import { Route as WorkflowIndexRouteImport } from './routes/workflow.index'
import { Route as WorkflowWorkflowIdRouteImport } from './routes/workflow.$workflowId'
import { Route as FormTableNameIndexRouteImport } from './routes/form.$tableName.index'
import { Route as FormTableNameRecordIdRouteImport } from './routes/form.$tableName.$recordId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderTableNameRoute = BuilderTableNameRouteImport.update({
  id: '/builder/$tableName',
  path: '/builder/$tableName',
  getParentRoute: () => rootRouteImport,
} as any)
const ListTableNameRoute = ListTableNameRouteImport.update({
  id: '/list/$tableName',
  path: '/list/$tableName',
  getParentRoute: () => rootRouteImport,
} as any)
const UiBuilderIndexRoute = UiBuilderIndexRouteImport.update({
  id: '/ui-builder/',
  path: '/ui-builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiBuilderPageIdRoute = UiBuilderPageIdRouteImport.update({
  id: '/ui-builder/$pageId',
  path: '/ui-builder/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetBuilderIndexRoute = WidgetBuilderIndexRouteImport.update({
  id: '/widget-builder/',
  path: '/widget-builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetBuilderWidgetIdRoute = WidgetBuilderWidgetIdRouteImport.update({
  id: '/widget-builder/$widgetId',
  path: '/widget-builder/$widgetId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIndexRoute = WorkflowIndexRouteImport.update({
  id: '/workflow/',
  path: '/workflow/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowWorkflowIdRoute = WorkflowWorkflowIdRouteImport.update({
  id: '/workflow/$workflowId',
  path: '/workflow/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormTableNameIndexRoute = FormTableNameIndexRouteImport.update({
  id: '/form/$tableName/',
  path: '/form/$tableName/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormTableNameRecordIdRoute = FormTableNameRecordIdRouteImport.update({
  id: '/form/$tableName/$recordId',
  path: '/form/$tableName/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/builder/$tableName': typeof BuilderTableNameRoute
  '/list/$tableName': typeof ListTableNameRoute
  '/ui-builder/$pageId': typeof UiBuilderPageIdRoute
  '/widget-builder/$widgetId': typeof WidgetBuilderWidgetIdRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/ui-builder/': typeof UiBuilderIndexRoute
  '/widget-builder/': typeof WidgetBuilderIndexRoute
  '/workflow/': typeof WorkflowIndexRoute
  '/form/$tableName/$recordId': typeof FormTableNameRecordIdRoute
  '/form/$tableName/': typeof FormTableNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/builder/$tableName': typeof BuilderTableNameRoute
  '/list/$tableName': typeof ListTableNameRoute
  '/ui-builder/$pageId': typeof UiBuilderPageIdRoute
  '/widget-builder/$widgetId': typeof WidgetBuilderWidgetIdRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/ui-builder': typeof UiBuilderIndexRoute
  '/widget-builder': typeof WidgetBuilderIndexRoute
  '/workflow': typeof WorkflowIndexRoute
  '/form/$tableName/$recordId': typeof FormTableNameRecordIdRoute
  '/form/$tableName': typeof FormTableNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/builder/$tableName': typeof BuilderTableNameRoute
  '/list/$tableName': typeof ListTableNameRoute
  '/ui-builder/$pageId': typeof UiBuilderPageIdRoute
  '/widget-builder/$widgetId': typeof WidgetBuilderWidgetIdRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/ui-builder/': typeof UiBuilderIndexRoute
  '/widget-builder/': typeof WidgetBuilderIndexRoute
  '/workflow/': typeof WorkflowIndexRoute
  '/form/$tableName/$recordId': typeof FormTableNameRecordIdRoute
  '/form/$tableName/': typeof FormTableNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/builder/$tableName'
    | '/list/$tableName'
    | '/ui-builder/$pageId'
    | '/widget-builder/$widgetId'
    | '/workflow/$workflowId'
    | '/ui-builder/'
    | '/widget-builder/'
    | '/workflow/'
    | '/form/$tableName/$recordId'
    | '/form/$tableName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/builder/$tableName'
    | '/list/$tableName'
    | '/ui-builder/$pageId'
    | '/widget-builder/$widgetId'
    | '/workflow/$workflowId'
    | '/ui-builder'
    | '/widget-builder'
    | '/workflow'
    | '/form/$tableName/$recordId'
    | '/form/$tableName'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/builder/$tableName'
    | '/list/$tableName'
    | '/ui-builder/$pageId'
    | '/widget-builder/$widgetId'
    | '/workflow/$workflowId'
    | '/ui-builder/'
    | '/widget-builder/'
    | '/workflow/'
    | '/form/$tableName/$recordId'
    | '/form/$tableName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  BuilderTableNameRoute: typeof BuilderTableNameRoute
  ListTableNameRoute: typeof ListTableNameRoute
  UiBuilderPageIdRoute: typeof UiBuilderPageIdRoute
  WidgetBuilderWidgetIdRoute: typeof WidgetBuilderWidgetIdRoute
  WorkflowWorkflowIdRoute: typeof WorkflowWorkflowIdRoute
  UiBuilderIndexRoute: typeof UiBuilderIndexRoute
  WidgetBuilderIndexRoute: typeof WidgetBuilderIndexRoute
  WorkflowIndexRoute: typeof WorkflowIndexRoute
  FormTableNameRecordIdRoute: typeof FormTableNameRecordIdRoute
  FormTableNameIndexRoute: typeof FormTableNameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$tableName': {
      id: '/builder/$tableName'
      path: '/builder/$tableName'
      fullPath: '/builder/$tableName'
      preLoaderRoute: typeof BuilderTableNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$tableName': {
      id: '/list/$tableName'
      path: '/list/$tableName'
      fullPath: '/list/$tableName'
      preLoaderRoute: typeof ListTableNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-builder/': {
      id: '/ui-builder/'
      path: '/ui-builder'
      fullPath: '/ui-builder/'
      preLoaderRoute: typeof UiBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-builder/$pageId': {
      id: '/ui-builder/$pageId'
      path: '/ui-builder/$pageId'
      fullPath: '/ui-builder/$pageId'
      preLoaderRoute: typeof UiBuilderPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget-builder/': {
      id: '/widget-builder/'
      path: '/widget-builder'
      fullPath: '/widget-builder/'
      preLoaderRoute: typeof WidgetBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget-builder/$widgetId': {
      id: '/widget-builder/$widgetId'
      path: '/widget-builder/$widgetId'
      fullPath: '/widget-builder/$widgetId'
      preLoaderRoute: typeof WidgetBuilderWidgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/': {
      id: '/workflow/'
      path: '/workflow'
      fullPath: '/workflow/'
      preLoaderRoute: typeof WorkflowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$workflowId': {
      id: '/workflow/$workflowId'
      path: '/workflow/$workflowId'
      fullPath: '/workflow/$workflowId'
      preLoaderRoute: typeof WorkflowWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$tableName/': {
      id: '/form/$tableName/'
      path: '/form/$tableName'
      fullPath: '/form/$tableName/'
      preLoaderRoute: typeof FormTableNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$tableName/$recordId': {
      id: '/form/$tableName/$recordId'
      path: '/form/$tableName/$recordId'
      fullPath: '/form/$tableName/$recordId'
      preLoaderRoute: typeof FormTableNameRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  BuilderTableNameRoute: BuilderTableNameRoute,
  ListTableNameRoute: ListTableNameRoute,
  UiBuilderPageIdRoute: UiBuilderPageIdRoute,
  WidgetBuilderWidgetIdRoute: WidgetBuilderWidgetIdRoute,
  WorkflowWorkflowIdRoute: WorkflowWorkflowIdRoute,
  UiBuilderIndexRoute: UiBuilderIndexRoute,
  WidgetBuilderIndexRoute: WidgetBuilderIndexRoute,
  WorkflowIndexRoute: WorkflowIndexRoute,
  FormTableNameRecordIdRoute: FormTableNameRecordIdRoute,
  FormTableNameIndexRoute: FormTableNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
