/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BuilderTableNameRouteImport } from './routes/builder.$tableName'
import { Route as ListTableNameRouteImport } from './routes/list.$tableName'
import { Route as FormTableNameIndexRouteImport } from './routes/form.$tableName.index'
import { Route as FormTableNameRecordIdRouteImport } from './routes/form.$tableName.$recordId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderTableNameRoute = BuilderTableNameRouteImport.update({
  id: '/builder/$tableName',
  path: '/builder/$tableName',
  getParentRoute: () => rootRouteImport,
} as any)
const ListTableNameRoute = ListTableNameRouteImport.update({
  id: '/list/$tableName',
  path: '/list/$tableName',
  getParentRoute: () => rootRouteImport,
} as any)
const FormTableNameIndexRoute = FormTableNameIndexRouteImport.update({
  id: '/form/$tableName/',
  path: '/form/$tableName/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormTableNameRecordIdRoute = FormTableNameRecordIdRouteImport.update({
  id: '/form/$tableName/$recordId',
  path: '/form/$tableName/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/builder/$tableName': typeof BuilderTableNameRoute
  '/list/$tableName': typeof ListTableNameRoute
  '/form/$tableName/$recordId': typeof FormTableNameRecordIdRoute
  '/form/$tableName/': typeof FormTableNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/builder/$tableName': typeof BuilderTableNameRoute
  '/list/$tableName': typeof ListTableNameRoute
  '/form/$tableName/$recordId': typeof FormTableNameRecordIdRoute
  '/form/$tableName': typeof FormTableNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/builder/$tableName': typeof BuilderTableNameRoute
  '/list/$tableName': typeof ListTableNameRoute
  '/form/$tableName/$recordId': typeof FormTableNameRecordIdRoute
  '/form/$tableName/': typeof FormTableNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/builder/$tableName'
    | '/list/$tableName'
    | '/form/$tableName/$recordId'
    | '/form/$tableName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/builder/$tableName'
    | '/list/$tableName'
    | '/form/$tableName/$recordId'
    | '/form/$tableName'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/builder/$tableName'
    | '/list/$tableName'
    | '/form/$tableName/$recordId'
    | '/form/$tableName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  BuilderTableNameRoute: typeof BuilderTableNameRoute
  ListTableNameRoute: typeof ListTableNameRoute
  FormTableNameRecordIdRoute: typeof FormTableNameRecordIdRoute
  FormTableNameIndexRoute: typeof FormTableNameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$tableName': {
      id: '/builder/$tableName'
      path: '/builder/$tableName'
      fullPath: '/builder/$tableName'
      preLoaderRoute: typeof BuilderTableNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$tableName': {
      id: '/list/$tableName'
      path: '/list/$tableName'
      fullPath: '/list/$tableName'
      preLoaderRoute: typeof ListTableNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$tableName/': {
      id: '/form/$tableName/'
      path: '/form/$tableName'
      fullPath: '/form/$tableName/'
      preLoaderRoute: typeof FormTableNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$tableName/$recordId': {
      id: '/form/$tableName/$recordId'
      path: '/form/$tableName/$recordId'
      fullPath: '/form/$tableName/$recordId'
      preLoaderRoute: typeof FormTableNameRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  BuilderTableNameRoute: BuilderTableNameRoute,
  ListTableNameRoute: ListTableNameRoute,
  FormTableNameRecordIdRoute: FormTableNameRecordIdRoute,
  FormTableNameIndexRoute: FormTableNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
